module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/ByKln8fmosq65h9zpFUrSk',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: '',
    NEWSLETTER_JID: '120363423792937578@newsletter',
    NEWSLETTER_MESSAGE_ID: '120363405381898232@newsletter',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'DOBERTO-XD',
    OWNER_NAME: 'Dev Doberto',
    OWNER_NUMBER: '00000000000,00000000000',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> DOBERTO-XD',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBulmY0LKZLRooVdU0i',
};
